### ISSUE TITLE
Better usage.

### ISSUE THREAD

**Issue by wrexwaz** [starmatt/youtube-ftw#1]
Hi.
Make better turning OFF with mouse wheel down and ON with mouse wheel up.
When we turn on wideo it will be of full and when we want to see comments or something, turning mouse wheel down wil be exiting this mode and normaly scrolling page. And when we want full screen back it will be on when page goes to top with mouse wheel. (like was in YouTube Center)
WIDEO: https://streamable.com/kdzr9

Sorry for lang.

**Comment by starmatt** [comment]
Thank you for the feature request, it's a good idea. I'll see what I can do!

**Comment by starmatt** [comment]
Feature added in version 1.2
